# Generated by Django 4.0.1 on 2022-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user_id', models.CharField(db_index=True, max_length=200)),
                ('box_img', models.ImageField(blank=True, upload_to='boxs/%Y/%m/%d')),
                ('box_content', models.TextField()),
                ('num_of_like', models.IntegerField()),
            ],
            options={
                'index_together': {('id', 'user_id')},
            },
        ),
    ]
