# Generated by Django 4.0.1 on 2022-01-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField()),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField()),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='user_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
