# Generated by Django 4.0.1 on 2022-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_comment_like_box_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_img',
            field=models.ImageField(blank=True, upload_to='boxs/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['box_id'], name='box_comment_box_id_00604e_idx'),
        ),
    ]
