# Generated by Django 4.0.1 on 2022-01-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_alter_box_box_img_alter_box_user_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('box_id', models.IntegerField()),
                ('bookmark', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='box_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='box',
            name='user_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
