# Generated by Django 4.0.1 on 2022-01-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_active_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.EmailField(max_length=255)),
                ('following', models.EmailField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
