# Generated by Django 4.0.1 on 2022-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, default='basic_user.png', upload_to='users/'),
        ),
    ]
